export const ICONS = [
    { label: "Website / Globe", class: "fas fa-globe" },
    { label: "Email / Envelope", class: "fas fa-envelope" },
    { label: "WhatsApp", class: "fab fa-whatsapp" },
    { label: "Facebook", class: "fab fa-facebook" },
    { label: "LinkedIn", class: "fab fa-linkedin" },
    { label: "Instagram", class: "fab fa-instagram" },
    { label: "Twitter / X", class: "fab fa-twitter" },
    { label: "Youtube", class: "fab fa-youtube" },
    { label: "Tiktok", class: "fab fa-tiktok" },
    { label: "Telegram", class: "fab fa-telegram" },
    { label: "Phone", class: "fas fa-phone" },
    { label: "Map Marker", class: "fas fa-map-marker-alt" },

    // Productivity / Apps
    { label: "Chart / Pie", class: "fas fa-chart-pie" },
    { label: "Chart / Line", class: "fas fa-chart-line" },
    { label: "Bullhorn / Promo", class: "fas fa-bullhorn" },
    { label: "Camera", class: "fas fa-camera" },
    { label: "Camera Retro", class: "fas fa-camera-retro" },
    { label: "Pen / Edit", class: "fas fa-pen" },
    { label: "Robot / AI", class: "fas fa-robot" },
    { label: "Brain", class: "fas fa-brain" },
    { label: "Lightbulb", class: "fas fa-lightbulb" },
    { label: "Rocket", class: "fas fa-rocket" },
    { label: "Book", class: "fas fa-book" },
    { label: "Calendar", class: "fas fa-calendar-alt" },
    { label: "Clock", class: "fas fa-clock" },
    { label: "Cloud", class: "fas fa-cloud" },
    { label: "Code", class: "fas fa-code" },
    { label: "Database", class: "fas fa-database" },
    { label: "File", class: "fas fa-file-alt" },
    { label: "Folder", class: "fas fa-folder" },
    { label: "Image", class: "fas fa-image" },
    { label: "Link", class: "fas fa-link" },
    { label: "Money", class: "fas fa-money-bill-wave" },
    { label: "Shopping Cart", class: "fas fa-shopping-cart" },
    { label: "User", class: "fas fa-user" },
    { label: "Users", class: "fas fa-users" },
    { label: "Star", class: "fas fa-star" },
    { label: "Heart", class: "fas fa-heart" },
    { label: "Check", class: "fas fa-check" },
    { label: "Video", class: "fas fa-video" }
];
